### PR TITLE
Added clearInstance method call.

### PR DESCRIPTION
**Pull request by osvarychevskyi**
Added clearInstance method call to reduce memory usage during product export.

### CODE REVIEW

**Comment by bobbyshaw** [comment]
I don't see this in master, has there not been another release? I ran into this issue today.

**Comment by Bobspadger** [comment]
+1 for this to be merged into master

**Comment by xpoback** [comment]
Thanks for contribution, guys.

**Comment by Bobspadger** [comment]
Nice., thanks :-)

**Pull request merged**
