### PR TITLE
Faster image and deeplink export

### PR DESCRIPTION
**Pull request by marcharding**
This improves speed when images and deeplinks are exported. 

In my test cases the export now takes about 50% less time and uses 10% less memory than before (ymmv).

### CODE REVIEW

**Comment by tuegeb** [comment]
@xpoback: Could you check whether this improvement could be integrated into the version 4.x, please?

**Comment by xpoback** [comment]
@marcharding Many thanks for your contribution!
@tuegeb I integrated this to the current version, also added saving the image, since it was missing.
At my test instance it used about 50% less time and about 15% less memory (PHP7.0), especially in cases when no cache images were created yet.

**Comment by xpoback** [comment]
This should also fix the issue in #173

**Comment by tuegeb** [comment]
@xpoback: I can confirm that it solves #173, too. Many thanks.

**Pull request closed without merging**
